version: "3.4"

services:
  plex:
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - plex_config:/config
      - plex_transcode:/transcode
      - plex_data:/data

  deluge:
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - deluge_downloads:/config
      - deluge_config:/downloads

  jellyfin:
    ports:
      - 8096:8096
    expose:
      - 8096
    volumes:
      - jellyfin_cache:/cache
      - jellyfin_config:/config
      - jellyfin_data:/media

  mariadb:
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  # redis:
  #   volumes:
  #     - redis:/data

  # owncloud:
  #   ports:
  #     - ${OWNCLOUD_PORT:-8080}:8080
  #   volumes:
  #     - owncloud_files:/mnt/data

  filerun:
    volumes:
      - filerun_html:/var/www/html
      - filerun_user_files:/user-files

  caddy:
    environment:
      PLEX_HOST: plex
      JELLYFIN_HOST: jellyfin
      DELUGE_HOST: deluge
      OWNCLOUD_HOST: owncloud
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp

volumes:
  caddy_data:
  caddy_config:
  owncloud_files:
  mariadb:
  redis:
  jellyfin_data:
  jellyfin_config:
  jellyfin_cache:
  deluge_downloads:
  deluge_config:
  plex_data:
  plex_transcode:
  plex_config:
  filerun_html:
  filerun_user_files:
