version: "3.4"

services:
  plex:
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  deluge:
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp

  jellyfin:
    ports:
      - 8096:8096
    expose:
      - 8096

  owncloud:
    ports:
      - ${OWNCLOUD_PORT:-8080}:8080

  caddy:
    environment:
      PLEX_HOST: plex
      JELLYFIN_HOST: jellyfin
      DELUGE_HOST: deluge
      OWNCLOUD_HOST: owncloud
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
