version: "3.4"

services:
  plex:
    build:
      context: .
      target: app_pms
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      PLEX_DATA: ${PLEX_DATA:-./plexdata}
      TZ: ${TIMEZONE:-Europe/Brussels}
    hostname: ${PLEX_HOSTNAME:-plexmediaserver}
    volumes:
      - ${PLEX_DATA:-./plexdata}/database:/config
      - ${PLEX_DATA:-./plexdata}/transcode:/transcode
      - ${PLEX_DATA:-./plexdata}/media:/data

  caddy:
    build:
      context: .
      target: app_caddy
    restart: unless-stopped
    depends_on:
      - plex
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
