version: "3.4"

services:
  plex:
    ports:
      - ${PLEX_WEB_PORT:-32400}:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${PLEX_DATA:-./plexdata}/database:/config
      - ${PLEX_DATA:-./plexdata}/transcode:/transcode
      - ${PLEX_DATA:-./plexdata}/media:/data

  jellyfin:
    ports:
      - 8096:8096
    volumes:
      - ${JELLYFIN_CONFIG:-./docker/jellyfin/config}:/config
      - ${JELLYFIN_CACHE:-./docker/jellyfin/cache}:/cache
      - ${JELLYFIN_MEDIA:-./docker/jellyfin/media}:/media

  deluge:
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ${DELUGE_CONFIG_DIR:-./docker/deluge/config}:/config
      - ${DELUGE_DOWNLOADS_DIR:-./docker/deluge/downloads}:/downloads

  mariadb:
    volumes:
      - ${MARIADB_DIR:-./docker/mariadb/data}:/var/lib/mysql

  filerun:
    volumes:
      - ${FILERUN_USER_FILES}:/user-files

  caddy:
    network_mode: host
    volumes:
      - ${CADDY_DATA_DIR:-./docker/caddy/data}:/data
      - ${CADDY_CONFIG_DIR:-./docker/caddy/config}:/config
