version: "3.4"

services:
  plex:
    network_mode: host
    volumes:
      - ${PLEX_DATA:-./plexdata}/database:/config
      - ${PLEX_DATA:-./plexdata}/transcode:/transcode
      - ${PLEX_DATA:-./plexdata}/media:/data

  # jellyfin:
  #   network_mode: host
  #   volumes:
  #     - ${JELLYFIN_CONFIG:-./docker/jellyfin/config}:/config
  #     - ${JELLYFIN_CACHE:-./docker/jellyfin/cache}:/cache
  #     - ${JELLYFIN_MEDIA:-./docker/jellyfin/media}:/media

  deluge:
    network_mode: host
    volumes:
      - ${DELUGE_CONFIG_DIR:-./docker/deluge/config}:/config
      - ${DELUGE_DOWNLOADS_DIR:-./docker/deluge/downloads}:/downloads

  # mariadb:
  #   volumes:
  #     - ${MARIADB_DIR:-./docker/mariadb/data}:/var/lib/mysql

  # filerun:
  #   ports:
  #     - ${FILERUN_PORT:-8080}:80
  #   volumes:
  #     - ${FILERUN_USER_FILES}:/user-files

  caddy:
    network_mode: host
    environment:
      PLEX_HOST: localhost
      JELLYFIN_HOST: localhost
      DELUGE_HOST: localhost
      FILERUN_HOST: localhost
    volumes:
      - ${CADDY_DATA_DIR:-./docker/caddy/data}:/data
      - ${CADDY_CONFIG_DIR:-./docker/caddy/config}:/config
