version: "3.4"

services:
  plex:
    build:
      context: .
      target: app_pms
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      PLEX_DATA: ${PLEX_DATA:-./plexdata}
      TZ: ${TIMEZONE:-Europe/Brussels}
      PLEX_HOSTNAME: ${PLEX_HOSTNAME:-plexmediaserver}
      PLEX_CLAIM: ${PLEX_CLAIM:-no}
    hostname: ${PLEX_HOSTNAME:-plexmediaserver}
    volumes:
      - ${PLEX_DATA:-./plexdata}/database:/config
      - ${PLEX_DATA:-./plexdata}/transcode:/transcode
      - ${PLEX_DATA:-./plexdata}/media:/data

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: host
    environment:
      PUID: ${DELUGE_UID:-1000}
      PGID: ${DELUGE_GID:-1000}
      TZ: ${TIMEZONE:-Europe/Brussels}
      DELUGE_LOGLEVEL: ${DELUGE_LOGLEVEL:-error} #optional
    volumes:
      - ./docker/deluge/config:/config
      - ${DELUGE_DOWNLOADS_DIR:-./docker/deluge/downloads}:/downloads
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: host
    user: ${DELUGE_UID:-1000}:${DELUGE_GID:-1000}
    volumes:
      - ./docker/jellyfin/config:/config
      - ./docker/jellyfin/cache:/cache
      - ${JELLYFIN_MEDIA:-./docker/jellyfin/media}:/media
    restart: unless-stopped

  caddy:
    build:
      context: .
      target: app_caddy
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - plex
      - deluge
      - jellyfin
    network_mode: host
    environment:
      PLEX_SERVER_NAME: ${PLEX_SERVER_NAME:-plex.local}
      DELUGE_SERVER_NAME: ${DELUGE_SERVER_NAME:-deluge.local}
      JELLYFIN_SERVER_NAME: ${JELLYFIN_SERVER_NAME:-jellyfin.local}
    volumes:
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
