version: "3.4"

services:
  plex:
    network_mode: host
  jellyfin:
    network_mode: host
  deluge:
    network_mode: host
  owncloud:
    network_mode: host
    volumes:
      - ${OWNCLOUD_DATA_DIR:-./docker/owncloud/data}:/mnt/data
  caddy:
    network_mode: host
    volumes:
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
