#!/bin/bash

RUN_ENV=dev
SKIP_DOWN=1
LOGS=0

function down {
  echo "Bring everything down"
  docker compose down --remove-orphans
}

function rebuild {
  echo "Rebuilding"
  docker compose build --pull --no-cache
}

function startDev() {
  echo "Starting with DEV env"
  docker compose up -d
}

function startProd() {
  echo "Starting with PROD env"
  if [ $1 -eq 1 ]; then
    docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d \
      && docker compose logs -f caddy
  else
    docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
  fi
}

while getopts 'de:l' OPTION; do
  case "$OPTION" in
    d)
      SKIP_DOWN=0
      ;;
    e)
      RUN_ENV=$OPTARG
      ;;
    l)
      LOGS=1
      ;;
    *)
      RUN_ENV=dev
      ;;
  esac
done

if [ $SKIP_DOWN -eq 0 ]; then
  down
fi

rebuild

if [ $RUN_ENV == "prod" ]; then
  startProd $LOGS
else
  startDev $LOGS
fi
